routes/admin.php
          Route::name('admin.graduations_rules.store')->post('/adicionar', 'Graduations\GraduationRuleController@store');
          Route::name('admin.graduations_rules.edit')->get('/editar/{id}', 'Graduations\GraduationRuleController@edit');
          Route::name('admin.graduations_rules.update')->put('/editar/{id}', 'Graduations\GraduationRuleController@update');
          Route::name('admin.graduations_rules.destroy')->delete('/excluir/{id}', 'Graduations\GraduationRuleController@destroy');
        });
      });

      // Bills
      Route::prefix('contas')->group(function() {
        Route::name('admin.bills.index')->get('/', 'Bills\BillController@index');
        Route::name('admin.bills.show')->get('/visualizar/{id}', 'Bills\BillController@show');
        Route::name('admin.bills.create')->get('/adicionar', 'Bills\BillController@create');
        Route::name('admin.bills.store')->post('/adicionar', 'Bills\BillController@store');
        Route::name('admin.bills.edit')->get('/editar/{id}', 'Bills\BillController@edit');
        Route::name('admin.bills.update')->put('/editar/{id}', 'Bills\BillController@update');
        Route::name('admin.bills.destroy')->delete('/excluir/{id}', 'Bills\BillController@destroy');
      });

      // Bills Types
      Route::prefix('contas/tipos')->group(function() {
        Route::name('admin.bills_types.index')->get('/', 'Bills\BillTypeController@index');
        Route::name('admin.bills_types.create')->get('/adicionar', 'Bills\BillTypeController@create');
        Route::name('admin.bills_types.store')->post('/adicionar', 'Bills\BillTypeController@store');
        Route::name('admin.bills_types.edit')->get('/editar/{id}', 'Bills\BillTypeController@edit');
        Route::name('admin.bills_types.update')->put('/editar/{id}', 'Bills\BillTypeController@update');
        Route::name('admin.bills_types.destroy')->delete('/excluir/{id}', 'Bills\BillTypeController@destroy');
      });

      // Bills Items
      Route::prefix('contas/items')->group(function() {
        Route::name('admin.bills_items.index')->get('/', 'Bills\BillItemController@index');
        Route::name('admin.bills_items.create')->get('/adicionar', 'Bills\BillItemController@create');
        Route::name('admin.bills_items.store')->post('/adicionar', 'Bills\BillItemController@store');
        Route::name('admin.bills_items.edit')->get('/editar/{id}', 'Bills\BillItemController@edit');
        Route::name('admin.bills_items.update')->put('/editar/{id}', 'Bills\BillItemController@update');
        Route::name('admin.bills_items.destroy')->delete('/excluir/{id}', 'Bills\BillItemController@destroy');
      });

      // Modalities
      Route::prefix('modalidades')->group(function() {
        Route::name('admin.modalities.index')->get('/', 'Modalities\ModalityController@index');
        Route::name('admin.modalities.create')->get('/adicionar', 'Modalities\ModalityController@create');
        Route::name('admin.modalities.store')->post('/adicionar', 'Modalities\ModalityController@store');
        Route::name('admin.modalities.edit')->get('/editar/{id}', 'Modalities\ModalityController@edit');
        Route::name('admin.modalities.update')->put('/editar/{id}', 'Modalities\ModalityController@update');
        Route::name('admin.modalities.destroy')->delete('/excluir/{id}', 'Modalities\ModalityController@destroy');
      });

      // Teachers
      Route::prefix('professores')->group(function() {
        Route::name('admin.teachers.index')->get('/', 'Teachers\TeacherController@index');
        Route::name('admin.teachers.show')->get('/visualizar/{code}', 'Teachers\TeacherController@show');
        Route::name('admin.teachers.create')->get('/adicionar', 'Teachers\TeacherController@create');
        Route::name('admin.teachers.store')->post('/adicionar', 'Teachers\TeacherController@store');
        Route::name('admin.teachers.edit')->get('/editar/{id}', 'Teachers\TeacherController@edit');
        Route::name('admin.teachers.update')->put('/editar/{id}', 'Teachers\TeacherController@update');
        Route::name('admin.teachers.destroy')->delete('/excluir/{id}', 'Teachers\TeacherController@destroy');
        Route::name('admin.teachers.sendEmail')->get('/reenviar-email/{id}', 'Teachers\TeacherController@sendEmail');
        Route::name('admin.teachers.activate')->get('/ativar/{id}', 'Teachers\TeacherController@activate');
        Route::name('admin.teachers.deactivate')->get('/desativar/{id}', 'Teachers\TeacherController@deactivate');
      });

      // Subscriptions
      Route::prefix('matriculas')->group(function() {
        Route::name('admin.subscriptions.index')->get('/', 'Subscriptions\SubscriptionController@index');
        Route::name('admin.subscriptions.show')->get('/visualizar/{code}', 'Subscriptions\SubscriptionController@show');
        Route::name('admin.subscriptions.create')->get('/adicionar', 'Subscriptions\SubscriptionController@create');
        Route::name('admin.subscriptions.store')->get('/adicionar/{id}', 'Subscriptions\SubscriptionController@store');
        Route::name('admin.subscriptions.edit')->get('/editar/{id}', 'Subscriptions\SubscriptionController@edit');
        Route::name('admin.subscriptions.update')->put('/editar/{id}', 'Subscriptions\SubscriptionController@update');
        Route::name('admin.subscriptions.destroy')->delete('/excluir/{id}', 'Subscriptions\SubscriptionController@destroy');
      });

      // Messages
      Route::prefix('mensagens')->group(function() {
        Route::name('admin.messages.index')->get('/{id?}', 'Messages\MessageController@index');
        Route::name('admin.messages.show')->get('/visualizar/{id}', 'Messages\MessageController@show');
        Route::name('admin.messages.edit')->get('/atualizar/{id}', 'Messages\MessageController@edit');
        Route::name('admin.messages.update')->put('/atualizar/{id}', 'Messages\MessageController@update');
        Route::name('admin.messages.destroy')->delete('/excluir/{id}', 'Messages\MessageController@destroy');
      });

      // Notifications
      Route::prefix('notificacoes')->group(function() {
        Route::name('admin.notifications.index')->get('/{id?}', 'Notifications\NotificationController@index');
        Route::name('admin.notifications.show')->get('/visualizar/{id}', 'Notifications\NotificationController@show');
        Route::name('admin.notifications.edit')->get('/atualizar/{id}', 'Notifications\NotificationController@edit');
        Route::name('admin.notifications.update')->put('/atualizar/{id}', 'Notifications\NotificationController@update');
        Route::name('admin.notifications.destroy')->delete('/excluir/{id}', 'Notifications\NotificationController@destroy');
      });

      // Account
      Route::prefix('perfil')->group(function() {
        Route::name('admin.accounts.show')->get('/', 'Users\AccountController@show');
        Route::name('admin.accounts.edit')->get('/atualizar', 'Users\AccountController@edit');
        Route::name('admin.accounts.update')->put('/atualizar', 'Users\AccountController@update');
      });

      // Permissions
      Route::prefix('permissoes')->group(function() {
        Route::name('admin.permissions.index')->get('/', 'Users\PermissionController@index');
        Route::name('admin.permissions.create')->get('/adicionar', 'Users\PermissionController@create');
        Route::name('admin.permissions.store')->post('/adicionar', 'Users\PermissionController@store');
        Route::name('admin.permissions.edit')->get('/editar/{id}', 'Users\PermissionController@edit');
        Route::name('admin.permissions.update')->put('/editar/{id}', 'Users\PermissionController@update');
        Route::name('admin.permissions.destroy')->delete('/excluir/{id}', 'Users\PermissionController@destroy');
      });

      // Roles
      Route::prefix('grupos')->group(function() {
        Route::name('admin.roles.index')->get('/', 'Users\RoleController@index');
        Route::name('admin.roles.create')->get('/adicionar', 'Users\RoleController@create');
        Route::name('admin.roles.store')->post('/adicionar', 'Users\RoleController@store');
        Route::name('admin.roles.edit')->get('/editar/{id}', 'Users\RoleController@edit');
        Route::name('admin.roles.update')->put('/editar/{id}', 'Users\RoleController@update');
      });

      // Users
      Route::prefix('usuarios')->group(function() {
        Route::name('admin.users.index')->get('/', 'Users\UserController@index');
        Route::name('admin.users.create')->get('/adicionar', 'Users\UserController@create');
        Route::name('admin.users.store')->post('/adicionar', 'Users\UserController@store');
        Route::name('admin.users.edit')->get('/editar/{id}', 'Users\UserController@edit');
        Route::name('admin.users.update')->put('/editar/{id}', 'Users\UserController@update');
        Route::name('admin.users.sendEmail')->get('/reenviar-email/{id}', 'Users\UserController@sendEmail');
        Route::name('admin.users.activate')->get('/ativar/{id}', 'Users\UserController@activate');
        Route::name('admin.users.deactivate')->get('/desativar/{id}', 'Users\UserController@deactivate');
      });

      // Settings
      Route::prefix('configuracoes')->group(function() {
        Route::name('admin.settings.index')->get('/', 'Settings\SettingController@index');
        Route::name('admin.settings.create')->get('/adicionar', 'Settings\SettingController@create');
        Route::name('admin.settings.store')->post('/adicionar', 'Settings\SettingController@store');
        Route::name('admin.settings.edit')->get('/editar/{id}', 'Settings\SettingController@edit');
        Route::name('admin.settings.update')->put('/editar/{id}', 'Settings\SettingController@update');
        Route::name('admin.settings.destroy')->delete('/excluir/{id}', 'Settings\SettingController@destroy');
      });

      // Audit
      Route::prefix('auditoria')->group(function() {

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.dashboard.index');
});

app/Models/Core/Audit.php
<?php

namespace App\Models\Core;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Audit as AuditContract;
use OwenIt\Auditing\Audit as AuditTrait;
use Carbon\Carbon;

class Audit extends Model implements AuditContract
{
  use AuditTrait;

  protected $guarded = [];

  protected $casts = [
    'old_values' => 'json',
    'new_values' => 'json'
  ];

  /**
   * Scopes
  */
  public function scopeToday($query)
  {
    $query->whereDate('created_at', Carbon::today());
  }

  /**
   * Accesors
   */
  public function getTypeNameAttribute()
  {
    $auditableType = class_basename($this->auditable_type);

    // Get types
    $types = config('qualitare.audit.types');

    // Return type name
    return isset($types[$auditableType]) ? $types[$auditableType] : 'Indefinido';
  }

  public function getActionNameAttribute()
  {
    // Get actions
    $actions = config('qualitare.audit.actions');

    // Return action name
    return $actions[$this->event];
  }
}

app/Models/Tuition/Tuition.php
<?php

namespace App\Models\Tuition;

use App\Models\Order\Order;
use App\Models\Student\Student;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Tuition extends Model
{
  protected $fillable = [
    'code',
    'schedule',
    'status',
    'descont',
    'signature',
    'amount',
    'type',
    'active',
    'isSchedule',
    'student_id',
  ];

  protected $dates = [
    'schedule',
  ];

  protected $casts = [
    'active' => 'boolean',
    'signature' => 'boolean',
    'isSchedule' => 'boolean',
  ];

  /**
   * The "booting" method of the model.
   *
   * @return void
   */
  protected static function boot()
  {
    parent::boot();

    static::creating(function ($model)
    {
      $model->configs();
    });
  }

  /**
   * Configs
   */
  protected function configs()
  {
    // Set code
    $this->attributes['code'] = sha1(date('dmyhis') . $this->student->cpf_or_cnpj . $this->student->full_name);
    $this->attributes['active'] = true;

    if ($this->type == 2) {
      $this->attributes['status'] = 1;
    } else {
      $this->attributes['status'] = 2;
    }

    if (!$this->isToday) {
      $this->attributes['status'] = 4;
    }
  }

  /**
   * Scopes
   */

  /**
   * Relationships
   */
  public function student()
  {
    return $this->belongsTo(Student::class, 'student_id');
  }

  public function orders()
  {
    return $this->belongsToMany(Order::class, 'tuitions_orders', 'tuitions_id', 'order_id');
  }

  /**
   * Mutators
   */
  public function setScheduleAttribute($input)
  {
    if($input)
      $this->attributes['schedule'] = Carbon::createFromFormat('d/m/Y', $input)->format('Y-m-d');
  }

  public function setAmountAttribute($value)
  {
    $this->attributes['amount'] = ($value != null) ? str_replace(['.', ','], ['', '.'], $value) : null;
  }

  public function setDescontAttribute($value)
  {
    $this->attributes['descont'] = ($value != null) ? str_replace(['.', ','], ['', '.'], $value) : null;
  }

  /**
   * Accesors
   */

  public function getReferenceAttribute()
  {
    return "#" . str_pad($this->id, 4, '0', STR_PAD_LEFT);
  }

  public function getTotalAttribute()
  {
    $amount = $this->amount;

    if ($this->descont) {
      $amount = $this->amount - $this->descont;
    }

    return number_format($amount, 2);
  }

  public function getTypeNameAttribute()
  {
    $name = null;

    switch ($this->type) {
      case 1:
        $name = 'Presencial';
        break;
      case 2:
        $name = 'Virtual';
        break;
    }

    return $name;
  }

  public function getStatusNameAttribute()
  {
    $name = null;

    switch ($this->status) {
      case 1:
        $name = 'Aguardando pagamento';
        break;
      case 2:
        $name = 'Pagamento efetuado';
        break;
      case 3:
        $name = 'Em atraso';
        break;
      case 4:
        $name = "Agendado em {$this->schedule->format('d/m/Y')}";
        break;
    }

    return $name;
  }

  public function getSendDateAttribute()
  {
    return $this->schedule->format('d/m/Y');
  }

  public function getStatusBadgeAttribute()
  {
    $status_name = '';

    switch($this->status):
      case 1:
        $status_name = '<span class="badge badge-info -info">Aguardando pagamento</span>';
        break;
      case 2:
        $status_name = '<span class="badge badge-success -status">Pagamento Efetuado</span>';
        break;
      case 3:
        $status_name = '<span class="badge badge-success -status">Em atraso</span>';
        break;
      case 4:
        $status_name = "<span class='badge badge-warning -status'>Agendado em {$this->sendDate}</span>";
        break;
    endswitch;

    return $status_name;
  }

  public function getActiveNameAttribute()
  {
    return $this->active ? 'Sim'  : 'Não';
  }

  public function getScheduleNameAttribute()
  {
    return $this->isSchedule ? 'Sim'  : 'Não';
  }

  public function getIsTodayAttribute()
  {
    return $this->schedule->lte(Carbon::now());
  }
}

app/Http/Controllers/Admin/Audits/AuditController.php
<?php

namespace App\Http\Controllers\Admin\Audits;

use App\Http\Controllers\Admin\BaseController;
use Illuminate\Http\Request;
use Artesaos\SEOTools\Traits\SEOTools as SEOToolsTrait;
use Crumbs;
use Auth;
use App\Models\Core\Audit;
use App\Models\Auth\User;
use Carbon\Carbon;

class AuditController extends BaseController
{
  use SEOToolsTrait;

  private $audits;
  private $users;

  public function __construct(Audit $audits, User $users)
  {
    // Middlewares
    $this->middleware('permission:view_audits', ['only' => ['index', 'show']]);

    // Dependency Injection
    $this->audits = $audits;
    $this->users = $users;
  }

  /**
   * Display a listing of the resource.
   * @return Response
   */
  public function index(Request $request)
  {
    // Fetch all users
    $users = $this->users->select('id', 'first_name', 'last_name')->byRole(['atendimento', 'gestor', 'root'])->get()->pluck('full_name', 'id');

    // Start query
    $query = $this->audits->latest();

    // Get types
    $types = config('qualitare.audit.types');

    // Get actions
    $actions = config('qualitare.audit.actions');

    // Filter by data param
    if ($request->filled('data')):
      $date = Carbon::createFromFormat('d-m-Y', $request->get('data'))->format('Y-m-d');
      $query->whereDate('created_at', $date);
    endif;

    // Filter by usuario param
    if ($request->filled('usuario')):
      $query->where('user_id', $request->get('usuario'));
    endif;

    // Filter by tipo param
    if ($request->filled('tipo')):
      $query->where('type', $request->get('tipo'));
    endif;

    // Filter by acao param
    if ($request->filled('acao')):
      $query->where('event', $request->get('acao'));
    endif;

    // Fetch all results
    $results = $query->paginate(5)->appends($request->except('page'));

    // Set meta tags
    $this->seo()->setTitle('Auditoria');

    // Return view
    return view('admin.audits.index', compact('results', 'users', 'types', 'actions'));
  }

  /**
   * Show the specified resource.
   * @return Response
   */
  public function show($id)
  {
    // Fetch result by id
    $result = $this->audits->findOrFail($id);

    // Set meta tags
    $this->seo()->setTitle('Auditoria - Log');

    // Return view
    return view('admin.audits.show', compact('result'));
  }
}

resources/views/admin/audits/index.blade.php
@extends('admin.layouts.default')

@section('content')

  <section class="section">
    <div class="section-header">
      <h1>Auditoria</h1>
      {!! Breadcrumbs::render('audits.index') !!}
    </div>

    <div class="row">
      <div class="col-12">
        <div class="card mb-0">
          <div class="card-body">
            {!! Form::open(['class' => 'form', 'novalidate', 'route' => 'admin.audits.index', 'method' => 'GET']) !!}
              <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-12 mb-0 form-group">
                  {!! Form::text('data', Request::get('data'), ['class' => 'form-control js-datepicker', 'placeholder' => 'Data']) !!}
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 mb-0 form-group">
                  {!! Form::select('usuario', $users, Request::get('usuario'), ['class' => 'form-control', 'placeholder' => 'Usuário']) !!}
                </div>
                <div class="col-lg-2 col-md-2 col-sm-12 mb-0 form-group">
                  {!! Form::select('tipo', $types, Request::get('tipo'), ['class' => 'form-control', 'placeholder' => 'Tipo']) !!}
                </div>

                <div class="col-lg-2 col-md-2 col-sm-12 mb-0 form-group">
                  {!! Form::select('acao', $actions, Request::get('acao'), ['class' => 'form-control', 'placeholder' => 'Ação ']) !!}
                </div>
                <div class="col-lg-1 col-md-1 col-sm-12 mb-0 form-group">
                  <a href="#" class="btn btn-icon btn-block btn-danger">
                    <i class="fas fa-ban lg-icon"></i>
                  </a>
                </div>
                <div class="col-lg-1 col-md-1 col-sm-12 mb-0 form-group">
                  <button type="submit" class="btn btn-icon btn-block btn-success">
                    <i class="fas fa-search lg-icon"></i>
                  </button>
                </div>
              </div>
           {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>

    <div class="section-body">
      <div class="row mt-4">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h4>
                <i class="far fa-star"></i>
                Listagem de Auditoria <br>
                <small>{{ $results->total() }} resultados.</small>
              </h4>
            </div>
            <div class="card-body -table">
              <div class="table-responsive">
                <table class="table table-striped">
                  <tbody>
                  <tr>
                    <th>Usuário</th>
                    <th>Tipo</th>
                    <th>Ação</th>
                    <th>Horário</th>
                    <th>Ações</th>
                  </tr>
                  @foreach($results as $result)
                    <tr>
                      <td>
                       <img src="{{ $result->user->photo }}" alt="{{ $result->user->full_name }}" width="25">
                       {{ $result->user->full_name }}
                     </td>
                      <td>{{ $result->type_name }}</td>
                      <td>{{ $result->action_name }}</td>
                      <td>{{ $result->created_at->format('d/m/Y H:i') }}</td>
                      <td class="no-wrap">
                        @can('view_audits')
                          <a href="{{ route('admin.audits.show', ['id' => $result->id]) }}" data-toggle="tooltip" data-placement="top" title="" data-original-title="Visualizar"> <i class="icon far fa-eye lg"></i></a>
                        @endcan
                      </td>
                    </tr>
                  @endforeach
                  </tbody>
                </table>
              </div>
            </div>
            <div class="card-footer">
              <div class="float-right">
                <nav>
                  {!! $results->render() !!}
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/admin/audits/show.blade.php
@extends('admin.layouts.default')

@section('content')

  <section class="section">
    <div class="section-header mb-0">
      <h1>Visualizar</h1>
      {!! Breadcrumbs::render('audits.show', $result) !!}
    </div>
    <div class="section-options">
      @can('view_audits')
        <div class="text-right mb-2">
          <a href="{{ route('admin.audits.index') }}" class="btn btn-lg btn-danger btn-icon" title="Voltar"><i class="fas fa-angle-left"></i> Voltar</a>
        </div>
      @endcan
    </div>
    <div class="clearfix"></div>
    <div class="section-body">
      <div class="row">
        <div class="col-12 col-md-4 col-lg-4">
          <div class="card">
            <div class="card-header -warning">
              <h4>
                <i class="far fa-user mr-2 lga"></i> Auditor
              </h4>
            </div>
            <div class="card-body">
              <div class="mb-2">
                <b>Nome  </b><span clas="text-muted">{{ $result->user->full_name }}</span>
                <br>
                <b>E-mail  </b><span clas="text-muted">{{ $result->user->email }}</span>
              </div>
            </div>
          </div>
          <div class="card">
            <div class="card-header">
              <h4>
                <i class="fas fa-cog mr-2 lga"></i> Log
              </h4>
            </div>
            <div class="card-body">
              <div class="mb-2">
                <span clas="text-muted">{{ $result->created_at->formatLocalized('%d %B %Y') }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection