routes/admin.php
<?php

/**
* Admin Routes
*/
Route::prefix('admin')->group(function() {

  /**
  * Auto login
  */
  Route::name('autologin')->middleware('guest.admin')->get('/autologin/{token}', '\Watson\Autologin\AutologinController@autologin');

  /**
  * Public Routes
  */
  Route::middleware('guest.admin')->namespace('Admin\Sessions')->group(function() {
    // Login
    Route::name('admin.session.login')->get('/acessar', 'SessionController@showLoginForm');
    Route::name('admin.session.login')->post('/acessar', 'SessionController@login');

    // Social Login
    Route::name('admin.social.redirect')->get('/social/redirect/{provider}', 'SocialController@redirectToProvider');
    Route::name('admin.social.handle')->get('/social/handle/{provider}', 'SocialController@handleProviderCallback');

    // Reset Password
    Route::name('admin.password.forgot')->get('/esqueci-minha-senha', 'ForgotPasswordController@showLinkRequestForm');
    Route::name('admin.password.processForgot')->post('/esqueci-minha-senha', 'ForgotPasswordController@sendResetLinkEmail');
    Route::name('admin.password.reset')->get('/cadastrar-senha/{token}/{email}', 'ResetPasswordController@showResetForm');
    Route::name('admin.password.processReset')->post('/cadastrar-senha', 'ResetPasswordController@reset');

    // First access
    Route::name('admin.activation.create')->get('/primeiro-acesso/{token}', 'ActivationController@showActivationForm');
    Route::name('admin.activation.processCreate')->post('/primeiro-acesso/{token}', 'ActivationController@store');
  });

  /**
   * Protected Routes
   */
  Route::middleware(['auth.admin'])->group(function() {

    // Logout
    Route::name('admin.session.logout')->get('/sair', 'Admin\Sessions\SessionController@logout');

    // Api
    Route::prefix('api')->namespace('Api')->group(function() {
      Route::name('api.modalities.filter')->get('/filtrar-categorias/{slug?}', 'Modalities\ModalityController@filter');
    });

    // Check first access
    Route::middleware('first.access')->namespace('Admin')->group(function() {

      // Dashboards
      Route::name('admin.dashboard.index')->get('/', 'Dashboard\DashboardController@index');

      // Dashboards
      Route::name('admin.birthdays.index')->get('/aniversariantes', 'Birthdays\BirthdayController@index');

      // Students frequencies
      Route::prefix('frequencias')->group(function() {
        Route::name('admin.students_frequencies.index')->get('/', 'Student\Frequencies\FrequencyController@index');
        Route::name('admin.students_frequencies.show')->get('/visualizar/{id}', 'Student\Frequencies\FrequencyController@show');
        Route::name('admin.students_frequencies.create')->get('/adicionar', 'Student\Frequencies\FrequencyController@create');
        Route::name('admin.students_frequencies.store')->post('/adicionar', 'Student\Frequencies\FrequencyController@store');
        Route::name('admin.students_frequencies.edit')->get('/editar/{id}', 'Student\Frequencies\FrequencyController@edit');
        Route::name('admin.students_frequencies.update')->put('/editar/{id}', 'Student\Frequencies\FrequencyController@update');
        Route::name('admin.students_frequencies.destroy')->delete('/excluir/{id}', 'Student\Frequencies\FrequencyController@destroy');
      });
      ;

       // Students graduations
      Route::prefix('graduacoes')->group(function() {
        Route::name('admin.students_graduations.index')->get('/', 'Student\Graduations\GraduationController@index');
        Route::name('admin.students_graduations.show')->get('/visualizar/{id}', 'Student\Graduations\GraduationController@show');
        Route::name('admin.students_graduations.create')->get('/adicionar', 'Student\Graduations\GraduationController@create');
        Route::name('admin.students_graduations.store')->post('/adicionar', 'Student\Graduations\GraduationController@store');
        Route::name('admin.students_graduations.edit')->get('/editar/{id}', 'Student\Graduations\GraduationController@edit');
        Route::name('admin.students_graduations.update')->put('/editar/{id}', 'Student\Graduations\GraduationController@update');
        Route::name('admin.students_graduations.destroy')->delete('/excluir/{id}', 'Student\Graduations\GraduationController@destroy');
      });

      // Students
      Route::prefix('alunos')->group(function() {
        Route::name('admin.students.index')->get('/', 'Students\StudentController@index');
        Route::name('admin.students.show')->get('/visualizar/{code}', 'Students\StudentController@show');
        Route::name('admin.students.create')->get('/adicionar', 'Students\StudentController@create');
        Route::name('admin.students.store')->post('/adicionar', 'Students\StudentController@store');
        Route::name('admin.students.edit')->get('/editar/{id}', 'Students\StudentController@edit');
        Route::name('admin.students.update')->put('/editar/{id}', 'Students\StudentController@update');
        Route::name('admin.students.destroy')->delete('/excluir/{id}', 'Students\StudentController@destroy');
        Route::name('admin.students.subscription')->post('/nova-matricula/{code}', 'Students\StudentController@subscription');
        Route::name('admin.students.band')->post('/nova-faixa/{code}', 'Students\StudentController@band');
        Route::name('admin.students.fisic')->post('/aptidao-fisica/{code}', 'Students\StudentController@fisic');

        // Students Tuitions
        Route::prefix('{code}/mensalidades')->group(function() {
          Route::name('admin.students_tuitions.index')->get('/', 'Students\StudentTuitionController@index');
          Route::name('admin.students_tuitions.show')->get('/visualizar/{id}', 'Students\StudentTuitionController@show');
          Route::name('admin.students_tuitions.create')->get('/adicionar', 'Students\StudentTuitionController@create');
          Route::name('admin.students_tuitions.store')->post('/adicionar', 'Students\StudentTuitionController@store');
          Route::name('admin.students_tuitions.destroy')->delete('/excluir/{id}', 'Students\StudentTuitionController@destroy');
        });

        // Students Origins
        Route::prefix('origens')->group(function() {
          Route::name('admin.students_origins.index')->get('/', 'Students\StudentOriginController@index');
          Route::name('admin.students_origins.create')->get('/adicionar', 'Students\StudentOriginController@create');
          Route::name('admin.students_origins.store')->post('/adicionar', 'Students\StudentOriginController@store');
          Route::name('admin.students_origins.edit')->get('/editar/{id}', 'Students\StudentOriginController@edit');
          Route::name('admin.students_origins.update')->put('/editar/{id}', 'Students\StudentOriginController@update');
          Route::name('admin.students_origins.destroy')->delete('/excluir/{id}', 'Students\StudentOriginController@destroy');
        });
      });

      // Orders
      Route::prefix('pedidos')->group(function() {
        Route::name('admin.orders.index')->get('/', 'Orders\OrderController@index');
        Route::name('admin.orders.show')->get('/visualizar/{code}', 'Orders\OrderController@show');
      });

      // Classrooms
      Route::prefix('turmas')->group(function() {
        Route::name('admin.classrooms.index')->get('/', 'Classrooms\ClassroomController@index');
        Route::name('admin.classrooms.show')->get('/visualizar/{id}', 'Classrooms\ClassroomController@show');
        Route::name('admin.classrooms.create')->get('/adicionar', 'Classrooms\ClassroomController@create');
        Route::name('admin.classrooms.store')->post('/adicionar', 'Classrooms\ClassroomController@store');
        Route::name('admin.classrooms.edit')->get('/editar/{id}', 'Classrooms\ClassroomController@edit');
        Route::name('admin.classrooms.update')->put('/editar/{id}', 'Classrooms\ClassroomController@update');
        Route::name('admin.classrooms.destroy')->delete('/excluir/{id}', 'Classrooms\ClassroomController@destroy');

        // Classrooms Frequencies
        Route::prefix('{classroom_id}/frequencias')->group(function() {
          Route::name('admin.classrooms_frequencies.index')->get('/', 'Classrooms\ClassroomFrequencyController@index');
          Route::name('admin.classrooms_frequencies.show')->get('/visualizar/{id}', 'Classrooms\ClassroomFrequencyController@show');
          Route::name('admin.classrooms_frequencies.create')->get('/adicionar', 'Classrooms\ClassroomFrequencyController@create');
          Route::name('admin.classrooms_frequencies.store')->post('/adicionar', 'Classrooms\ClassroomFrequencyController@store');
          Route::name('admin.classrooms_frequencies.edit')->get('/editar/{id}', 'Classrooms\ClassroomFrequencyController@edit');
          Route::name('admin.classrooms_frequencies.update')->put('/editar/{id}', 'Classrooms\ClassroomFrequencyController@update');
          Route::name('admin.classrooms_frequencies.destroy')->delete('/excluir/{id}', 'Classrooms\ClassroomFrequencyController@destroy');
        });
      });

      // Bands
      Route::prefix('faixas')->group(function() {
        Route::name('admin.bands.index')->get('/', 'Bands\BandController@index');
        Route::name('admin.bands.create')->get('/adicionar', 'Bands\BandController@create');
        Route::name('admin.bands.store')->post('/adicionar', 'Bands\BandController@store');
        Route::name('admin.bands.edit')->get('/editar/{id}', 'Bands\BandController@edit');
        Route::name('admin.bands.update')->put('/editar/{id}', 'Bands\BandController@update');
        Route::name('admin.bands.destroy')->delete('/excluir/{id}', 'Bands\BandController@destroy');
        Route::name('admin.bands.reorder')->post('/reordenar', 'Bands\BandController@reorder');

        // Bands Categories
        Route::prefix('categorias')->group(function() {
          Route::name('admin.bands_categories.index')->get('/', 'Bands\BandCategoryController@index');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.dashboard.index');
});

app/Models/Bill/Bill.php
<?php

namespace App\Models\Bill;

use App\Models\Auth\User;
use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable as AuditableInterface;
use OwenIt\Auditing\Auditable as AuditableTrait;
use Carbon\Carbon;

class Bill extends Model implements AuditableInterface
{
  use AuditableTrait;

  protected $fillable = [
    'code',
    'type',
    'date',
    'value',
    'type_id',
    'user_id',
    'active'
  ];

  protected $casts = [
    'active' => 'boolean'
  ];

  protected $dates = [
    'date'
  ];

  /**
  * Auditable Config
  */
  protected $auditInclude = [
    'code',
    'type',
    'date',
    'value',
    'type_id',
    'user_id',
    'active'
  ];

  /**
  * The "booting" method of the model.
  *
  * @return void
  */
  protected static function boot()
  {
    parent::boot();

    static::creating(function ($model)
    {
      $model->configs();
    });
  }

   /**
  * Configs
  */
  protected function configs()
  {
    // Set code
    $this->attributes['code'] = sha1(date('dmyhis') . $this->user->full_name);
  }

  /**
  * Scopes
  */
  public function scopeAsc($query)
  {
    return $query->orderBy('name', 'ASC');
  }

  public function scopeActive($query)
  {
    $query->whereActive(true);
  }

  /**
  * Relationships
  */
  public function user()
  {
    return $this->belongsTo(User::class, 'user_id');
  }

  public function typeRelation()
  {
    return $this->belongsTo(BillType::class, 'type_id');
  }

  public function billable()
  {
    return $this->morphTo();
  }

  /**
  * Mutators
  */
  public function setDateAttribute($input)
  {
    if($input)
      $this->attributes['date'] = Carbon::createFromFormat('d/m/Y', $input)->format('Y-m-d');
  }

  public function setValueAttribute($value)
  {
    $this->attributes['value'] = ($value != null) ? str_replace(['.', ','], ['', '.'], $value) : null;
  }

  /**
  * Accessors
  */
  public function getReferenceAttribute()
  {
    return "#" . str_pad($this->id, 4, '0', STR_PAD_LEFT);
  }

  public function getFormatNameAttribute()
  {
    $type = null;

    switch ($this->type) {
      case 1:
       $type = 'Mensal';
        break;
      case 2:
       $type = 'Anual';
        break;
      case 3:
        $type = 'Outros';
        break;
    }

    return $type;
  }
}

app/Models/Tuition/Tuition.php
<?php

namespace App\Models\Tuition;

use App\Models\Order\Order;
use App\Models\Student\Student;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Tuition extends Model
{
  protected $fillable = [
    'code',
    'schedule',
    'status',
    'descont',
    'signature',
    'amount',
    'type',
    'active',
    'isSchedule',
    'student_id',
  ];

  protected $dates = [
    'schedule',
  ];

  protected $casts = [
    'active' => 'boolean',
    'signature' => 'boolean',
    'isSchedule' => 'boolean',
  ];

  /**
   * The "booting" method of the model.
   *
   * @return void
   */
  protected static function boot()
  {
    parent::boot();

    static::creating(function ($model)
    {
      $model->configs();
    });
  }

  /**
   * Configs
   */
  protected function configs()
  {
    // Set code
    $this->attributes['code'] = sha1(date('dmyhis') . $this->student->cpf_or_cnpj . $this->student->full_name);
    $this->attributes['active'] = true;

    if ($this->type == 2) {
      $this->attributes['status'] = 1;
    } else {
      $this->attributes['status'] = 2;
    }

    if (!$this->isToday) {
      $this->attributes['status'] = 4;
    }
  }

  /**
   * Scopes
   */

  /**
   * Relationships
   */
  public function student()
  {
    return $this->belongsTo(Student::class, 'student_id');
  }

  public function orders()
  {
    return $this->belongsToMany(Order::class, 'tuitions_orders', 'tuitions_id', 'order_id');
  }

  /**
   * Mutators
   */
  public function setScheduleAttribute($input)
  {
    if($input)
      $this->attributes['schedule'] = Carbon::createFromFormat('d/m/Y', $input)->format('Y-m-d');
  }

  public function setAmountAttribute($value)
  {
    $this->attributes['amount'] = ($value != null) ? str_replace(['.', ','], ['', '.'], $value) : null;
  }

  public function setDescontAttribute($value)
  {
    $this->attributes['descont'] = ($value != null) ? str_replace(['.', ','], ['', '.'], $value) : null;
  }

  /**
   * Accesors
   */

  public function getReferenceAttribute()
  {
    return "#" . str_pad($this->id, 4, '0', STR_PAD_LEFT);
  }

  public function getTotalAttribute()
  {
    $amount = $this->amount;

    if ($this->descont) {
      $amount = $this->amount - $this->descont;
    }

    return number_format($amount, 2);
  }

  public function getTypeNameAttribute()
  {
    $name = null;

    switch ($this->type) {
      case 1:
        $name = 'Presencial';
        break;
      case 2:
        $name = 'Virtual';
        break;
    }

    return $name;
  }

  public function getStatusNameAttribute()
  {
    $name = null;

    switch ($this->status) {
      case 1:
        $name = 'Aguardando pagamento';
        break;
      case 2:
        $name = 'Pagamento efetuado';
        break;
      case 3:
        $name = 'Em atraso';
        break;
      case 4:
        $name = "Agendado em {$this->schedule->format('d/m/Y')}";
        break;
    }

    return $name;
  }

  public function getSendDateAttribute()
  {
    return $this->schedule->format('d/m/Y');
  }

  public function getStatusBadgeAttribute()
  {
    $status_name = '';

    switch($this->status):
      case 1:
        $status_name = '<span class="badge badge-info -info">Aguardando pagamento</span>';
        break;
      case 2:
        $status_name = '<span class="badge badge-success -status">Pagamento Efetuado</span>';
        break;
      case 3:
        $status_name = '<span class="badge badge-success -status">Em atraso</span>';
        break;
      case 4:
        $status_name = "<span class='badge badge-warning -status'>Agendado em {$this->sendDate}</span>";
        break;
    endswitch;

    return $status_name;
  }

  public function getActiveNameAttribute()
  {
    return $this->active ? 'Sim'  : 'Não';
  }

  public function getScheduleNameAttribute()
  {
    return $this->isSchedule ? 'Sim'  : 'Não';
  }

  public function getIsTodayAttribute()
  {
    return $this->schedule->lte(Carbon::now());
  }
}

resources/views/admin/students_tuitions/_form.blade.php
<div class="col-lg-12 col-sm-12">
  <div class="card">
    <div class="card-header -warning">
      <h4>
        <i class="far fa-edit lga"></i>
        Detalhes
      </h4>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-sm-12 col-md-4">
          <div class="form-group mb-2">
            {!! Form::label('schedule', 'Data da Cobrança', ['class' => '']) !!}
            {!! Form::text('schedule', old('date_begin'), ['class' => 'form-control js-datepicker']) !!}
            @if($errors->has('schedule'))
              <span class="text-danger">{{ $errors->first('schedule') }}</span>
            @endif
          </div>
        </div>
        <div class="col-sm-12 col-md-4">
          <div class="form-group mb-2">
            {!! Form::label('type', 'Forma de Pagamento', ['class' => '']) !!}
            {!! Form::select('type', [1 => 'Presencial', 2 => 'Virtual'], old('type'), ['class' => 'form-control', 'placeholder' => 'Selecione']) !!}
            @if($errors->has('type'))
              <span class="text-danger">{{ $errors->first('type') }}</span>
            @endif
          </div>
        </div>
        <div class="col-sm-12 col-md-4">
          <div class="form-group mb-2">
            {!! Form::label('amount', 'Preço', ['class' => '']) !!}
            {!! Form::text('amount', $student->modalities->count() > 0 ? $student->totalModalitiesSum : old('amount'), ['class' => 'form-control js-mask-money']) !!}
            @if($errors->has('amount'))
              <span class="text-danger">{{ $errors->first('amount') }}</span>
            @endif
          </div>
        </div>
        <div class="col-sm-12 col-md-4">
          <div class="form-group mb-2">
            {!! Form::label('descont', 'Desconto', ['class' => '']) !!}
            {!! Form::text('descont', old('descont'), ['class' => 'form-control js-mask-money']) !!}
            @if($errors->has('descont'))
              <span class="text-danger">{{ $errors->first('descont') }}</span>
            @endif
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<?php

resources/views/admin/students_tuitions/create.blade.php
@extends('admin.layouts.default')

@section('content')

  {!! Form::open(['method' => 'POST', 'novalidate', 'role' => 'form', 'class' => 'form', 'route' => ['admin.students_tuitions.store', 'code' => $student->code], 'files' => true]) !!}
  <section class="section">
    <div class="section-header mb-0">
      <h1>Nova Mensalidade</h1>
      {!! Breadcrumbs::render('students_tuitions.create', $student) !!}
    </div>

    <div class="section-options">
      <div class="text-right mb-2">
        <label class="mt-2 mr-2">
          {!! Form::hidden('signature', 0) !!}
          {!! Form::checkbox('signature', true, isset($result) ? $result->signature : false, ['class' => 'custom-switch-input', 'id' => 'signature']) !!}
          <span class="custom-switch-indicator"></span>
          <span class="custom-switch-description">Assinatura?</span>
        </label>
        <label class="mt-2 mr-2">
          {!! Form::hidden('isSchedule', 0) !!}
          {!! Form::checkbox('isSchedule', true, isset($result) ? $result->isSchedule : false, ['class' => 'custom-switch-input', 'id' => 'isSchedule']) !!}
          <span class="custom-switch-indicator"></span>
          <span class="custom-switch-description">Agendamento?</span>
        </label>
        <a href="{{ route('admin.students_tuitions.index', ['code' => $student->code]) }}" class="btn btn-danger btn-lg btn-icon mr-1" title="Voltar"><i class="fas fa-angle-left"></i> Voltar</a>
        <button type="submit" class="btn btn-icon icon-left btn-success btn-lg"><i class="fas fa-check"></i> Salvar</button>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="section-body">
      <div class="row">
        @include('admin.students_tuitions._form')
      </div>
    </div>
  </section>
  {!! Form::close() !!}

@endsection

resources/views/admin/students_tuitions/edit.blade.php
@extends('admin.layouts.default')

@section('content')

  {!! Form::model($result, ['method' => 'PUT', 'novalidate', 'role' => 'form', 'class' => 'form', 'route' => ['admin.students_origins.update', 'id' => $result->id, 'files' => true]]) !!}
  <section class="section">
    <div class="section-header mb-0">
      <h1>Editar Origem</h1>
      {!! Breadcrumbs::render('students_origins.edit', $result) !!}
    </div>

    <div class="section-options">
      <div class="text-right mb-2">
        <label class="mt-2 mr-2">
          {!! Form::hidden('active', 0) !!}
          {!! Form::checkbox('active', true, isset($result) ? $result->active : false, ['class' => 'custom-switch-input', 'id' => 'active']) !!}
          <span class="custom-switch-indicator"></span>
          <span class="custom-switch-description">Ativo?</span>
        </label>
        <a href="{{ route('admin.students_origins.index') }}" class="btn btn-danger btn-lg btn-icon mr-1" title="Voltar"><i class="fas fa-angle-left"></i> Voltar</a>
        <button type="submit" class="btn btn-icon icon-left btn-success btn-lg"><i class="fas fa-check"></i> Salvar</button>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="section-body">
      <div class="row">
        @include('admin.students_origins._form')
      </div>
    </div>
  </section>
  {!! Form::close() !!}

@endsection
<?php

resources/views/admin/students_tuitions/index.blade.php
@extends('admin.layouts.default')

@section('content')

  <section class="section">
    <div class="section-header mb-3">
      <h1>{{ $student->first_name }} - Mensalidades</h1>
      <div class="section-header-button mr-1">
       <a href="{{ route('admin.students.index') }}" class="btn btn-danger btn-icon btn-lg mr-2" title="Voltar"><i class="fas fa-arrow-left"></i> Voltar</a>
        @can('add_students_submodules')
          <a href="{{ route('admin.students_tuitions.create', ['code' => $student->code]) }}" class="btn btn-success btn-icon btn-lg" title="Adicionar"><i class="fas fa-plus"></i> Adicionar</a>
        @endcan
      </div>
      {!! Breadcrumbs::render('students_tuitions.index', $student) !!}
    </div>
    <div class="section-body">
      <div class="row mt-4">
        <div class="col-lg-12 col-sm-12">
          <h6 class="mb-3">Listagem de mensalidades</h6>
          <div class="card">
            <div class="card-body -table mb-0">
              <div class="table-responsive">
                <table class="table table-striped overflow mb-0">
                  <tbody>
                  <tr class="tr-a">
                    <th>Data da Cobrança</th>
                    <th>Preço</th>
                    <th>Tipo</th>
                    <th>Status</th>
                    <th>Ações</th>
                  </tr>
                  @foreach($results as $result)
                    <tr class="tr-item td-border">
                      <td class="td-item">{{ $result->schedule->format('d/m/Y') }}</td>
                      <td class="td-item">{{ money($result->total, 'BRL') }}</td>
                      <td class="td-item">{{ $result->typeName }}</td>
                      <td class="td-item">{!! $result->statusBadge !!}</td>
                      <td class="td-item">
                        @can('view_students_submodules')
                          <a href="{{ route('admin.students_tuitions.show', ['code' => $student->code, 'id' => $result->id]) }}" data-toggle="tooltip" data-placement="top" title="" data-original-title="Visualizar"> <i class="icon lg far fa-eye"></i></a>
                        @endcan

                        @can('delete_students_submodules')
                          <a  href="#" class="js-confirm-delete" data-link="{{ route('admin.students_tuitions.destroy', ['code' => $student->code, 'id' => $result->id]) }}" data-title="Mensalidade na data {{ $result->schedule->format('d/m/Y') }}"  data-toggle="tooltip" data-placement="top" title="" data-original-title="Excluir"> <i class="icon far fa-trash-alt lg"></i></a>
                        @endcan
                      </td>
                    </tr>
                  @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4 offset-md-3 col-lg-4 offset-lg-4 col-sm-12 mb-2">
          {!! $results->render() !!}
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/admin/students_tuitions/show.blade.php
@extends('admin.layouts.default')

@section('content')
  <section class="section">
    <div class="section-header mb-0">
      <h1>Visualizar Mensalidade - {{ $result->reference }}</h1>
      {!! Breadcrumbs::render('students_tuitions.show', $student, $result) !!}
    </div>
    <div class="section-options">
      <div class="text-right mb-2">
        <a href="{{ route('admin.students_tuitions.index', ['code' => $student->code]) }}" class="btn btn-lg btn-danger btn-icon mr-1" title="Voltar"><i class="fas fa-angle-left"></i> Voltar</a>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="section-body">
      <div class="row">
        <div class="col-12 col-md-4 col-lg-4">
          <div class="card">
            <div class="card-header">
              <h4><i class="fas fa-barcode lga"></i> Mensalidade</h4>
            </div>
            <div class="card-body -scroll-intern">
              <div class="mb-2">
                <b>Data da cobrança  </b><span class="text-muted">{{ $result->schedule->format('d/m/Y') }}</span>
              </div>
              <div class="mb-2">
                <b>Preço  </b><span class="text-muted">{{ money($result->total, 'BRL') }}</span>
              </div>
              @if($result->descont)
              <div class="mb-2">
                <b>Desconto  </b><span class="text-muted">{{ money($result->descont, 'BRL') }}</span>
              </div>
              @endif
              <div class="mb-2">
                <b>Tipo  </b><span class="text-muted">{{ $result->typeName }}</span>
              </div>
              <div class="mb-2">
                <b>Status  </b><span class="text-muted">{{ $result->statusName }}</span>
              </div>
              <div class="mb-2">
                <b>Ativo?  </b><span class="text-muted">{{ $result->activeName }}</span>
              </div>
              <div class="mb-2">
                <b>Assinatura?  </b><span class="text-muted">{{ $result->signatureName }}</span>
              </div>
              <div class="mb-2">
                <b>Agendamento?  </b><span class="text-muted">{{ $result->scheduleName }}</span>
              </div>
            </div>
          </div>
        </div>
        @if($result->orders->count() > 0)
        <div class="col-12 col-md-8 col-lg-8">
          <div class="card">
            <div class="card-header">
              <h4><i class="far fa-star lga"></i> Pedidos</h4>
            </div>
            <div class="card-body -table mb-0">
              <div class="table-responsive">
                <table class="table table-striped overflow mb-0">
                  <tbody>
                  <tr class="tr-a">
                    <th>#</th>
                    <th>Preço</th>
                    <th>Tipo</th>
                    <th>Data</th>
                    <th>Ações</th>
                  </tr>
                  @foreach($result->orders as $order)
                    <tr class="tr-item td-border">
                      <td class="td-item">{{ $order->reference }}</td>
                      <td class="td-item">{{ money(number_format($order->amount, 2), 'BRL') }}</td>
                      <td class="td-item">{{ $order->typeName }}</td>
                      <td class="td-item">{{ $order->created_at->format('d/m/Y H:i') }}</td>
                      <td class="td-item">
                        @can('view_students_submodules')
                          <a href="{{ route('admin.orders.show', ['code' => $order->code]) }}" data-toggle="tooltip" data-placement="top" title="" data-original-title="Visualizar"> <i class="icon lg far fa-eye"></i></a>
                        @endcan
                      </td>
                    </tr>
                  @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          @endif
        </div>
      </div>
    </div>
  </section>
@endsection